import type { StatusCategory } from "@/lib/status-categories";

function monitor(
  slug: string,
  name: string,
  category: StatusCategory,
  url: string,
  order: number,
) {
  return { slug, name, category, target: url, websiteUrl: url, order };
}

/**
 * Extra public checks: Ontario government and agencies, federal services
 * residents here use, Algoma municipalities, and Sault Ste. Marie
 * organizations. None of these are company-owned properties.
 */
export const MORE_STATUS_MONITORS = [
  // Ontario government
  monitor("ontario", "Government of Ontario", "Government", "https://www.ontario.ca/", 520),
  monitor("ontario-ministries", "Ontario ministries", "Government", "https://www.ontario.ca/page/ministries", 530),
  monitor("ontario-news", "Ontario Newsroom", "Government", "https://news.ontario.ca/", 540),
  monitor("ontario-data", "Ontario Data Catalogue", "Government", "https://data.ontario.ca/", 550),
  monitor("ontario-ohip", "OHIP and health cards", "Government", "https://www.ontario.ca/page/apply-ohip-and-get-health-card", 560),
  monitor("ontario-drivers-licence", "Ontario driver's licence", "Government", "https://www.ontario.ca/page/drivers-licence", 570),
  monitor("ontario-birth-certificate", "Ontario birth certificates", "Government", "https://www.ontario.ca/page/get-or-replace-ontario-birth-certificate", 580),
  monitor("ontario-change-address", "Ontario change of address", "Government", "https://www.ontario.ca/page/change-my-address-ontario-services", 590),
  monitor("odsp", "Ontario Disability Support Program", "Government", "https://www.ontario.ca/page/ontario-disability-support-program", 600),
  monitor("ontario-works", "Ontario Works", "Government", "https://www.ontario.ca/page/ontario-works", 610),
  monitor("osap", "OSAP", "Government", "https://www.ontario.ca/page/osap-ontario-student-assistance-program", 620),
  monitor("ontario-fishing", "Ontario fishing", "Government", "https://www.ontario.ca/page/fishing", 630),
  monitor("ontario-hunting", "Ontario hunting", "Government", "https://www.ontario.ca/page/hunting", 640),
  monitor("health811", "Health811", "Health", "https://health811.ontario.ca/static/guest/home", 650),
  monitor("ontario-emergency-rooms", "Ontario emergency rooms", "Emergency", "https://www.ontario.ca/page/emergency-rooms", 660),
  monitor("ontario-child-care", "Ontario child care", "Government", "https://www.ontario.ca/page/types-child-care", 670),
  monitor("ontario-long-term-care", "Ontario long-term care", "Health", "https://www.ontario.ca/page/apply-long-term-care", 680),
  monitor("drivetest", "DriveTest", "Government", "https://drivetest.ca/", 690),
  monitor("elections-ontario", "Elections Ontario", "Government", "https://www.elections.on.ca/", 700),
  monitor("ombudsman-ontario", "Ombudsman Ontario", "Government", "https://www.ombudsman.on.ca/", 710),
  monitor("auditor-general-ontario", "Auditor General of Ontario", "Government", "https://www.auditor.on.ca/", 720),
  monitor("ipc-ontario", "Information and Privacy Commissioner of Ontario", "Government", "https://www.ipc.on.ca/", 730),
  monitor("ohrc", "Ontario Human Rights Commission", "Government", "https://www.ohrc.on.ca/", 740),
  monitor("legal-aid-ontario", "Legal Aid Ontario", "Government", "https://www.legalaid.on.ca/", 750),
  monitor("tribunals-ontario", "Tribunals Ontario", "Government", "https://tribunalsontario.ca/", 760),
  monitor("ontario-courts", "Ontario Courts", "Government", "https://www.ontariocourts.ca/", 770),
  monitor("mpac", "MPAC", "Government", "https://www.mpac.ca/", 780),
  monitor("onland", "ONLAND land registry", "Government", "https://www.onland.ca/", 790),
  monitor("ontario-parks", "Ontario Parks", "Government", "https://www.ontarioparks.com/", 800),
  monitor("conservation-ontario", "Conservation Ontario", "Government", "https://conservationontario.ca/", 810),
  monitor("wsib", "WSIB", "Government", "https://www.wsib.ca/", 820),
  monitor("oeb", "Ontario Energy Board", "Utilities", "https://www.oeb.ca/", 830),
  monitor("ieso", "IESO", "Utilities", "https://www.ieso.ca/", 840),
  monitor("opg", "Ontario Power Generation", "Utilities", "https://www.opg.com/", 850),
  monitor("esa", "Electrical Safety Authority", "Utilities", "https://esasafe.com/", 860),
  monitor("tssa", "TSSA", "Government", "https://www.tssa.org/", 870),
  monitor("ontario-health", "Ontario Health", "Health", "https://www.ontariohealth.ca/", 880),
  monitor("public-health-ontario", "Public Health Ontario", "Health", "https://www.publichealthontario.ca/", 890),
  monitor("connexontario", "ConnexOntario", "Health", "https://www.connexontario.ca/", 900),
  monitor("rhra", "Retirement Homes Regulatory Authority", "Health", "https://www.rhra.ca/", 910),
  monitor("fsra", "FSRA", "Government", "https://www.fsrao.ca/", 920),
  monitor("osc", "Ontario Securities Commission", "Government", "https://www.osc.ca/", 930),
  monitor("agco", "AGCO", "Government", "https://www.agco.ca/", 940),
  monitor("lcbo", "LCBO", "Government", "https://www.lcbo.com/", 950),
  monitor("olg", "OLG", "Government", "https://www.olg.ca/", 960),
  monitor("ocs", "Ontario Cannabis Store", "Government", "https://ocs.ca/", 970),
  monitor("tvo", "TVO", "Education", "https://www.tvo.org/", 980),
  monitor("tfo", "TFO", "Education", "https://www.tfo.org/", 990),
  monitor("ouac", "OUAC", "Education", "https://www.ouac.on.ca/", 1000),
  monitor("ontario-colleges", "Ontario Colleges", "Education", "https://www.ontariocolleges.ca/", 1010),
  monitor("eqao", "EQAO", "Education", "https://www.eqao.com/", 1020),
  monitor("oct", "Ontario College of Teachers", "Education", "https://www.oct.ca/", 1030),
  monitor("contact-north", "Contact North", "Education", "https://contactnorth.ca/", 1040),
  monitor("workplace-safety-north", "Workplace Safety North", "Emergency", "https://www.workplacesafetynorth.ca/", 1050),
  monitor("ontario-northland", "Ontario Northland", "Travel", "https://www.ontarionorthland.ca/", 1060),
  monitor("metrolinx", "Metrolinx", "Travel", "https://www.metrolinx.com/", 1070),
  monitor("go-transit", "GO Transit", "Travel", "https://www.gotransit.com/", 1080),

  // Federal services Ontarians use
  monitor("canada", "Government of Canada", "Government", "https://www.canada.ca/", 1090),
  monitor("ircc", "Immigration, Refugees and Citizenship Canada", "Government", "https://www.canada.ca/en/immigration-refugees-citizenship.html", 1100),
  monitor("cbsa", "Canada Border Services Agency", "Government", "https://www.cbsa-asfc.gc.ca/", 1110),
  monitor("rcmp", "RCMP", "Emergency", "https://www.rcmp-grc.gc.ca/", 1120),
  monitor("health-canada", "Health Canada", "Health", "https://www.canada.ca/en/health-canada.html", 1130),
  monitor("transport-canada", "Transport Canada", "Travel", "https://tc.canada.ca/", 1140),
  monitor("job-bank", "Job Bank", "Government", "https://www.jobbank.gc.ca/", 1150),
  monitor("employment-insurance", "Employment Insurance", "Government", "https://www.canada.ca/en/services/benefits/ei.html", 1160),
  monitor("cpp", "Canada Pension Plan", "Government", "https://www.canada.ca/en/services/benefits/publicpensions/cpp.html", 1170),
  monitor("veterans-affairs", "Veterans Affairs Canada", "Government", "https://www.veterans.gc.ca/", 1180),
  monitor("passports", "Canadian passports", "Government", "https://www.canada.ca/en/immigration-refugees-citizenship/services/canadian-passports.html", 1190),
  monitor("nav-canada", "NAV CANADA", "Travel", "https://www.navcanada.ca/", 1200),
  monitor("via-rail", "VIA Rail", "Travel", "https://www.viarail.ca/", 1210),
  monitor("cbc", "CBC", "News", "https://www.cbc.ca/", 1220),
  monitor("radio-canada", "Radio-Canada", "News", "https://ici.radio-canada.ca/", 1230),
  monitor("canadian-blood-services", "Canadian Blood Services", "Health", "https://www.blood.ca/", 1240),

  // Algoma municipalities and local organizations
  monitor("prince-township", "Prince Township", "Government", "https://www.princetownship.ca/", 1250),
  monitor("blind-river", "Town of Blind River", "Government", "https://www.blindriver.ca/", 1260),
  monitor("elliot-lake", "City of Elliot Lake", "Government", "https://www.elliotlake.ca/", 1270),
  monitor("wawa", "Municipality of Wawa", "Government", "https://www.wawa.cc/", 1280),
  monitor("thessalon", "Town of Thessalon", "Government", "https://thessalon.ca/", 1290),
  monitor("ssm-friendship-centre", "Indigenous Friendship Centre of Sault Ste. Marie", "First Nations", "https://ssmifc.ca/", 1300),
  monitor("algoma-cas", "Children's Aid Society of Algoma", "Community", "https://algomacas.org/", 1310),
  monitor("algoma-legal-clinic", "Algoma Community Legal Clinic", "Community", "https://www.algomalegalclinic.com/", 1320),
  monitor("victim-services-algoma", "Victim Services of Algoma", "Emergency", "https://www.victimservicesalgoma.ca/", 1330),
  monitor("alzheimer-algoma", "Alzheimer Society Sault Ste. Marie and Algoma", "Health", "https://alzheimer.ca/algoma", 1340),
  monitor("habitat-sault", "Habitat for Humanity Sault Ste. Marie", "Community", "https://habitatsault.ca/", 1350),
  monitor("metis-nation-ontario", "Métis Nation of Ontario", "First Nations", "https://www.metisnation.org/", 1360),
  monitor("ofifc", "Ontario Federation of Indigenous Friendship Centres", "First Nations", "https://ofifc.org/", 1370),
  monitor("anishinabek", "Anishinabek Nation", "First Nations", "https://www.anishinabek.ca/", 1380),
  monitor("science-north", "Science North", "Community", "https://sciencenorth.ca/", 1390),
  monitor("kids-help-phone", "Kids Help Phone", "Emergency", "https://kidshelpphone.ca/", 1400),
  monitor("red-cross", "Canadian Red Cross", "Emergency", "https://www.redcross.ca/", 1410),
  monitor("salvation-army", "The Salvation Army", "Community", "https://www.salvationarmy.ca/", 1420),
  monitor("canadian-cancer-society", "Canadian Cancer Society", "Health", "https://cancer.ca/", 1430),
  monitor("heart-and-stroke", "Heart and Stroke", "Health", "https://www.heartandstroke.ca/", 1440),
  monitor("diabetes-canada", "Diabetes Canada", "Health", "https://www.diabetes.ca/", 1450),
  monitor("march-of-dimes", "March of Dimes Canada", "Community", "https://www.marchofdimes.ca/", 1460),
  monitor("cn-rail", "CN", "Travel", "https://www.cn.ca/", 1470),
  monitor("enbridge-gas", "Enbridge Gas", "Utilities", "https://www.enbridgegas.com/", 1480),
  monitor("eastlink", "Eastlink", "Utilities", "https://www.eastlink.ca/", 1490),
  monitor("stepstojustice", "Steps to Justice", "Community", "https://stepstojustice.ca/", 1500),
  monitor("college-of-nurses", "College of Nurses of Ontario", "Health", "https://www.cno.org/", 1510),
  monitor("cpso", "College of Physicians and Surgeons of Ontario", "Health", "https://www.cpso.on.ca/", 1520),
  monitor("bruce-mines", "Town of Bruce Mines", "Government", "https://www.brucemines.ca/", 1530),
  monitor("hiawatha-highlands", "Hiawatha Highlands", "Community", "https://hiawathahighlands.com/", 1540),
  monitor("big-brothers-big-sisters", "Big Brothers Big Sisters of Canada", "Community", "https://bigbrothersbigsisters.ca/", 1550),
  monitor("scouts-canada", "Scouts Canada", "Community", "https://www.scouts.ca/", 1560),
  monitor("st-john-ambulance", "St. John Ambulance", "Emergency", "https://sja.ca/", 1570),
  monitor("northern-ontario-business", "Northern Ontario Business", "News", "https://www.northernontariobusiness.com/", 1580),
  monitor("sudbury", "City of Greater Sudbury", "Government", "https://www.greatersudbury.ca/", 1590),
];
